### ISSUE TITLE
missing track doesn't download from host? 

### ISSUE THREAD

**Issue by SJacobs501** [gro-ove/ac-server-wrapper#4]
How do I host a server with just a missing layout? For instance, I want to host a custom Nordschleife layout using the ks_nordschleife track. If I add the track as ks_nordschleife in the server wrapper, CM will think I already have it and therefore not download the custom layout. Then upon entering the server it will give an error, "CHECKSUM MISMATCH" I believe.

**Comment by gro-ove** [comment]
Hmm, nope, CM will find out that layout is missing and will download it according to “track” field. If needed, here is [another example preset](https://drive.google.com/file/d/0B6GfX1zRa8pOT3pmbVFVdnk3SUU/view), with a custom layout of Highlands made by Topuz.
